# Generated by Django 3.1.3 on 2020-12-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janken', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='janken',
            name='ranking',
        ),
    ]
