# Generated by Django 3.1.3 on 2020-12-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janken', '0002_remove_janken_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='janken',
            old_name='result',
            new_name='win',
        ),
    ]
