# Generated by Django 3.1.3 on 2020-12-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janken', '0003_auto_20201218_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='janken',
            name='grade',
        ),
    ]
